/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-background": "#e1e2eb",
        "tertiary-fixed": "#dee2ec",
        "error-container": "#93000a",
        "tertiary-container": "#8c919a",
        "on-secondary-container": "#004b65",
        "outline": "#8b90a0",
        "on-tertiary-fixed": "#171c23",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "surface-tint": "#adc6ff",
        "surface": "#10131a",
        "on-primary-fixed": "#001a41",
        "tertiary": "#c2c7d0",
        "error": "#ffb4ab",
        "surface-container": "#1d2026",
        "on-tertiary": "#2c3138",
        "on-secondary-fixed": "#001e2b",
        "surface-container-high": "#272a31",
        "inverse-primary": "#005bc1",
        "surface-variant": "#32353c",
        "on-tertiary-fixed-variant": "#42474f",
        "secondary-fixed": "#c2e8ff",
        "surface-container-lowest": "#0b0e14",
        "surface-container-highest": "#32353c",
        "on-surface-variant": "#c1c6d7",
        "secondary-fixed-dim": "#75d1ff",
        "surface-bright": "#363940",
        "on-primary-fixed-variant": "#004493",
        "primary": "#adc6ff",
        "on-primary-container": "#00285c",
        "tertiary-fixed-dim": "#c2c7d0",
        "on-surface": "#e1e2eb",
        "outline-variant": "#414755",
        "secondary-container": "#00c1fd",
        "on-secondary": "#003548",
        "primary-container": "#4b8eff",
        "on-primary": "#002e69",
        "background": "#10131a",
        "secondary": "#8fd8ff",
        "surface-container-low": "#191c22",
        "on-tertiary-container": "#252a31",
        "inverse-on-surface": "#2e3037",
        "on-secondary-fixed-variant": "#004d67",
        "inverse-surface": "#e1e2eb",
        "on-error": "#690005",
        "surface-dim": "#10131a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "120px",
        "margin-page": "40px",
        "card-padding": "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-sm": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
